---
name: CI
on:
  push:
    branches:
      - main
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p logs/
          echo 'Environment/App/db' > logs/exclude.txt
      - uses: max/secret-scan@master
        with:
          exclude_path: logs/exclude.txt
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p logs/
      - name: Safety
        run: >
          pip install safety

          safety check -r Environment/App/app/flask/requirements.txt > logs/result-safety.txt
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.txt
      - name: Pyraider
        run: >
          pip install pyraider

          pyraider check -f Environment/App/app/flask/requirements.txt > logs/result-pyraider.txt
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.json
